CREATE TABLE meals.recipes
(
    recipe_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    name character(200) NOT NULL,
    PRIMARY KEY (recipe_id)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE meals.recipes
    OWNER to huygens;