CREATE TABLE meals.recipes_ingredients
(
    recipe_ingredient_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    recipe_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    PRIMARY KEY (recipe_ingredient_id),
    CONSTRAINT recipes_ingredients_recipes FOREIGN KEY (recipe_id)
        REFERENCES meals.recipes (recipe_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT recipes_ingredients_ingredients FOREIGN KEY (ingredient_id)
        REFERENCES meals.ingredients (ingredient_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
);

ALTER TABLE meals.recipes_ingredients
    OWNER to huygens;